config/routes.rb
Rails.application.routes.draw do
  root 'static#home'

  devise_for :users

  resources :followers, only: [:create, :destroy], param: :user_id

  resources :posts do
    resource :likes, only: [:create, :destroy], module: :posts
    resources :comments, only: [:show, :create, :new, :destroy], module: :posts
  end

  resources :users, only: [:show], param: :username, path: '' do
    resources :posts, only: [:show], module: :users
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  validates :body, presence: true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: "follower_id", class_name: "User"
  belongs_to :following, foreign_key: "following_id", class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true, counter_cache: true
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :image, attached: true
  has_one_attached :image

  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy

  accepts_nested_attributes_for :comments, reject_if: proc { |attributes| attributes["body"].blank? }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: true, presence: true

  has_one_attached :avatar

  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :follower_relationships, foreign_key: :following_id, class_name: "Follow", dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: "Follow", dependent: :destroy
  has_many :following, through: :following_relationships, source: :following

  def likes?(likeable)
    likeable.likes.where(user_id: id).any?
  end

  def follow(user_id)
    following_relationships.find_or_create_by(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.where(following_id: user_id).destroy_all
  end

  def follows?(user_id)
    following_relationships.where(following_id: user_id).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[avatar name username bio])
  end

end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def create
    if current_user.follow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def destroy
    if current_user.unfollow(@user.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/posts/comments_controller.rb
module Posts
  class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post

    def create
      @comment = @post.comments.build(comments_params.merge(user: current_user))

      if @comment.save
        PostCommentChannel.broadcast_to(@post, comment_created_params)
        # render partial: "posts/comments/comment", locals: { comment: @comment }
      else
        render partial: "posts/comments/error", locals: { comment: @comment }, status: :bad_request
      end
    end

    def show
      @comments = @post.comments
                       .where("created_at < ?", DateTime.parse(params[:last_result_timestamp]))
                       .order(created_at: :desc).limit(10)
    end

    def destroy
      @comment = @post.comments.find(params[:id])
      @comment.destroy
      PostCommentChannel.broadcast_to(@post, comment_destroyed_params)
    end

    private

    def comment_destroyed_params
      { action: :destroy, comment_id: @comment.id }
    end

    def comment_created_params
      { action: :created, html: comment_html }
    end

    def comment_html
      ApplicationController.renderer.render(
        partial: "posts/comments/comment",
        locals: { realtime: true, comment: @comment },
        format: :html
      )
    end

    def more_records?(post, last_result)
      post.comments.where("created_at < ?", last_result.created_at).any?
    end
    helper_method :more_records?

    def set_post
      @post = Post.find(params[:post_id])
    end

    def comments_params
      params.require(:comment).permit(:body)
    end
  end
end

app/controllers/posts/likes_controller.rb
module Posts
  class LikesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post

    def create
      @post.likes.where(user: current_user).first_or_create

      respond_to do |format|
        format.html { redirect_to user_post_path(@post.user.username, @post) }
        format.js
      end
    end

    def destroy
      @post.likes.where(user: current_user).destroy_all

      respond_to do |format|
        format.html { redirect_to user_post_path(@post.user.username, @post) }
        format.js
      end
    end

    private

    def set_post
      @post = Post.find(params[:post_id])
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.comments&.first&.user = current_user

    if @post.save
      redirect_to posts_path, notice: "Created Post"
    else
      render :new, notice: "Please try again!"
    end
  end

  def edit; end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(@post.user.username), notice: "Post deleted"
  end

  private

  def post_params
    params.require(:post).permit(:image, comments_attributes: [:body])
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home
    redirect_to posts_path if user_signed_in?
  end
end

app/controllers/users/posts_controller.rb
module Users
  class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user

    def show
      @post = @user.posts.with_attached_image.find(params[:id])
      @comments = @post.comments.order(created_at: :desc).limit(10)
      @comment = @post.comments.new
    end

    private

    def more_records?(post, last_result)
      post.comments.where("created_at < ?", last_result.created_at).any?
    end
    helper_method :more_records?

    def set_user
      @user = User.find_by_username!(params[:user_username])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by!(username: params[:username])
    @posts = @user.posts.with_attached_image.order(created_at: :desc)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def avatar_url_for(user, opts={})
    size = opts[:size] || 32

    if user.avatar.attached?
      user.avatar.variant(
        resize: "#{size}x#{size}!"
      )
    else
      hash = Digest::MD5.hexdigest(user.email.downcase)
      "https://secure.gravatar.com/avatar/#{hash}.png?s=#{size}"
    end
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/followers/create.js.erb
const partial = "<%= escape_javascript(render partial: "users/follow_button", locals: { user: @user })  %>"
document.querySelector('[data-behavior="user_<%= @user.id %>_follow_button"]').innerHTML = partial

app/views/followers/destroy.js.erb
const partial = "<%= escape_javascript(render partial: "users/follow_button", locals: { user: @user }) %>"
document.querySelector('[data-behavior="user_<%= @user.id %>_follow_button"]').innerHTML = partial

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <%= render 'shared/head' %>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'devise/shared/flash/app' %>

    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |f| %>
  <% if f.object.errors.any? %>
    <p>
      <%= pluralize(f.object.errors.count, "error") %> prevented the form from being saved:
    </p>

    <ul>
      <% f.object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.hidden_field :post, value: f.object %>

  <div class="form-group">
    <%= f.label :image, "Your image" %>
    <div class="custom-file">
      <%= f.file_field :image, class: "custom-file-input" %>
      <label class="custom-file-label">
        Select file...
      </label>
    </div>
  </div>

  <%= f.fields_for :comments, f.object.comments.new do |comment_form| %>
    <%= comment_form.label :body, "Comment"%>
    <%= comment_form.text_area :body, class: "form-control", placeholder: "Start the discussion by talking about your photo"  %>
  <% end %>

  <%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/posts/_likes.html.erb
<h5 class="text-muted">
  <%= @post.likes_count %>

  <% if current_user.present? && current_user.likes?(@post) %>
    <%= link_to post_likes_path(post), method: :delete, remote: true do %>
      <svg width="25px" height="25px" viewBox="0 0 20 18" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <g id="Page-1" stroke="none" stroke-width="1" fill-rule="evenodd">
          <g id="heart" fill="purple">
            <path d="M10,2.22 L9.39,1.62 C7.22743631,-0.425051064 3.8303981,-0.378715619 1.72441737,1.72455819 C-0.381563355,3.82783201 -0.432267941,7.22480781 1.61,9.39 L10,17.78 L18.39,9.38 C20.4322679,7.21480781 20.3815634,3.81783201 18.2755826,1.71455819 C16.1696019,-0.388715619 12.7725637,-0.435051064 10.61,1.61 L10,2.22 Z" id="Path"></path>
          </g>
        </g>
      </svg>
    <% end %>
  <% else %>
    <%= link_to post_likes_path(post), method: :post, remote: true do %>
      <svg width="25px" height="25px" viewBox="0 0 20 18" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <g id="Page-1" stroke="none" stroke-width="1" fill-rule="evenodd">
          <g id="heart" fill="grey">
            <path d="M10,2.22 L9.39,1.62 C7.22743631,-0.425051064 3.8303981,-0.378715619 1.72441737,1.72455819 C-0.381563355,3.82783201 -0.432267941,7.22480781 1.61,9.39 L10,17.78 L18.39,9.38 C20.4322679,7.21480781 20.3815634,3.81783201 18.2755826,1.71455819 C16.1696019,-0.388715619 12.7725637,-0.435051064 10.61,1.61 L10,2.22 Z" id="Path"></path>
          </g>
        </g>
      </svg>
    <% end %>
  <% end %>

</h5>

app/views/posts/_post.html.erb
<div class="col-sm-4">
  <div class="card">
    <div class="card-img-top">
      <%= link_to user_post_path(post.user.username, post.id) do %>
        <%= image_tag post.image.variant(resize_to_fill: [250, 250]), style: "width: 100%" %>
      <% end %>
    </div>
    <div class="card-body card-text mx-auto">
      <h5>
        <%= image_tag avatar_url_for(post.user, size: 48), class: "rounded-circle" %>
        <%= link_to post.user.username, user_path(post.user.username) %>
      </h5>
    </div>
  </div>
</div>

app/views/posts/comments/_comment.html.erb
<div class="row mb-3" data-comment-id="comment_<%= comment.id %>">
  <div class="col-sm-1">
    <%= image_tag avatar_url_for(comment.user, size: 48), class: "rounded-circle" %>
  </div>

  <div class="col-sm-11">
    <% unless local_assigns[:realtime].present? %>
      <% if comment.user_id == current_user&.id || (comment.commentable.user_id == current_user&.id) %>
        <small class="float-right">
          <%= link_to "Delete", post_comment_path(comment.commentable, comment),
                      method: :delete, remote: true, class: "text-muted",
                      data: { confirm: "Are you sure? This cannot be undone." } %>
        </small>
      <% end %>
    <% end %>

    <small><em><strong>Posted by: <%= comment.user.username %></strong> <%= comment.created_at %></em></small>

    <p><%= comment.body %></p>
  </div>
</div>

app/views/posts/comments/_error.html.erb
<% if comment.errors.any? %>
  <div class="alert alert-danger">
    Please fix the following errors:
    <% comment.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </div>
<% end %>

app/views/posts/comments/_form.html.erb
<div class="my-1">
  <div data-comments-list-target="newCommentErrors"></div>

  <%= form_with(model: [post, comment], html: {
    data: { type: "html", action: "ajax:success->comments-list#onPostSuccess ajax:error->comments-list#onPostError" } }) do |f| %>
    <%= f.text_area :body, class: "form-control", placeholder: "Say something nice.",
                    data: { "comments-list-target": "textarea" } %>
    <div class="mt-3 d-flex justify-content-end">
      <%= f.submit "Post comment", data: { disable_with: "Posting..." }, class: "btn btn-primary btn-sm rounded" %>
    </div>
  <% end %>
</div>

app/views/posts/comments/_pagination_links.html.erb
<% if last_result.present? && more_records?(post, last_result) %>
  <%= link_to "Load more", post_comment_path(post, last_result_timestamp: last_result.created_at),
              data: { disabled_with: '<div class="spinner-border text-dark" role="status"><span class="sr-only">Loading...</span></div>' },
              class: "text-muted underline", remote: true %>
<% end %>

app/views/posts/comments/show.js.erb
const nextPageCommentHTML = "<%= escape_javascript(
  render partial: 'posts/comments/comment', collection: @comments.reverse) %>"
const placeholder = document.createElement('div')
placeholder.innerHTML = nextPageCommentHTML

const updatedPaginationLinksHTML = "<%= escape_javascript(render partial: 'posts/comments/pagination_links',
  locals: { post: @post, last_result: @comments.reverse.first }) %>"

const paginationControls = document.querySelector('[data-behavior="pagination-controls"]')
paginationControls.innerHTML = updatedPaginationLinksHTML
paginationControls.insertAdjacentElement('afterend', placeholder)

app/views/posts/index.html.erb
<h1 class="mt-5 mb-3">Your Feed</h1>

<% if @posts.any? %>
  <% @posts.each_slice(3) do |slice| %>
    <div class="row mb-3">
      <% slice.each do |post| %>
        <%= render('post', post: post) %>
      <% end %>
    </div>
  <% end %>
<% else %>
  <div class="card">
    <div class="card-body p-5">
      <h5>No posts! Try following someone new!</h5>
    </div>
  </div>
<% end %>

app/views/posts/likes/create.js.erb
var likesContainer = document.querySelector('[data-behavior="post_<%= @post.id %>_likes"]')

likesContainer.innerHTML = "<%= escape_javascript(render partial: "posts/likes", locals: { post:@post }) %>"

app/views/posts/likes/destroy.js.erb
var likesContainer = document.querySelector('[data-behavior="post_<%= @post.id %>_likes"]')

likesContainer.innerHTML = "<%= escape_javascript(render partial: "posts/likes", locals: { post:@post }) %>"

app/views/posts/new.html.erb
<div class="container">
  <div class="justify-content-center align-items-center">
    <div class="row">
      <div class="col-md-8 col-lg-8 mx-auto my-5">
        <div class="card shadow">
          <div class="card-body p-5">
            <h2 class="my-3">Share something</h2>

            <hr />

            <%= render 'form', post: @post %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/shared/_head.html.erb
<head>
  <title>Rails Gram</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

</head>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to 'Railsgram', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li><%= link_to "Explore", root_path, class: "nav-link" %></li>
      </ul>

      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Upload", new_post_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to current_user.username, user_path(current_user.username), class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/_follow_button.html.erb
<% unless user == current_user %>
  <% if current_user.follows?(user.id) %>
    <%= link_to "Unfollow", follower_path(user_id: user.id), method: :delete,
                local: false, class: "btn btn-primary btn-sm",
                data: { disable_with: "Unfollowing..." } %>
  <% else %>
    <%= link_to "Follow", followers_path(user_id: user.id), method: :post,
                local: false, class: "btn btn-outline-primary btn-sm",
                data: { disable_with: "Following..." } %>
  <% end %>
<% end %>

app/views/users/posts/show.html.erb
<div class="row mt-5">
  <div class="col-sm-8 mx-auto">
    <div class="card shadow-sm">
      <div class="card-img-top py-3 px-3">
        <%= image_tag @post.image, style: "width: 100%" %>
      </div>
      <div class="card-footer mt-5 card-text">
        <div class="d-flex align-items-center justify-content-between">
          <h5>
            <%= image_tag avatar_url_for(@post.user, size: 32), class: "rounded-circle mr-2" %>
            <%= link_to @post.user.username, user_path(@post.user.username), class: "text-muted" %>

            <% if current_user.present? && @post.user_id == current_user.id %>
              <small>
                <%= link_to "Delete", post_path(@post),
                            class: "btn btn-sm btn-outline-danger",
                            method: :delete, data: {
                    confirm: "Are you sure? This cannot be undone"
                  } %>
              </small>
            <% end %>
          </h5>

          <div data-behavior="post_<%= @post.id %>_likes">
            <%= render(partial: "posts/likes", locals: { post: @post }) %>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

<div class="row mt-3">
  <div class="col-sm-8 mx-auto" data-controller="comments-list">
    <h3 class="mt-3 mb-4">Comments</h3>

    <div class="card shadow-sm" data-comments-list-target="postId" data-post-id="<%= @post.id %>">
      <div class="card-body py-4">
        <div data-comments-list-target="commentList">
          <% if @comments.any? %>
            <div data-behavior="pagination-controls" class="text-center">
              <%= render partial: "posts/comments/pagination_links",
                         locals: { post: @post, last_result: @comments.reverse.first } %>
            </div>
            <%= render(partial: "posts/comments/comment", collection: @comments.reverse) %>
          <% else %>
            <h6 data-comments-list-target="blankslateText">No comments yet. Can you leave one?</h6>
          <% end %>
        </div>
      </div>
    </div>

    <div class="card-footer py-3">
      <%= render("posts/comments/form", post: @post, comment: @comment) %>
    </div>

  </div>

</div>

app/views/users/show.html.erb
<div class="d-flex align-items-center justify-content-center mt-5">
  <div class="media mr-5 align-self-start">
    <%= image_tag avatar_url_for(@user, size: 128), class: "rounded-circle mr-4" %>
  </div>
  <div class="media">
    <div class="media-body">
      <div class="d-flex flex-row align-items-center justify-content-between">
        <h1>
          <%= @user.username %>
          <%= link_to 'Edit', edit_user_registration_path, class: 'ml-3 btn btn-secondary btn-sm' if current_user.id == @user.id %>
        </h1>

        <div class="ml-3" data-behavior="user_<%= @user.id %>_follow_button">
          <%= render "users/follow_button", user: @user %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="d-block align-items-center justify-content-center mt-5">
  <h2 class="text-center mb-4">Posts</h2>

  <% if @posts.any? %>
    <% @posts.each_slice(3) do |slice| %>
      <div class="row mb-3">
        <% slice.each do |post| %>
          <div class="col-sm-4">
            <div class="card">
              <div class="card-img-top">
                <%= link_to user_post_path(post.user.username, post.id) do %>
                  <%= image_tag post.image.variant(resize_to_fill: [250, 250]), style: "width: 100%" %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    No posts yet!
  <% end %>

</div>